# Folosim versiunea 3.8 pentru o compatibilitate largă cu Docker
version: '3.8'

services:
  # Serviciul Eureka, centrul de descoperire a serviciilor
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    networks:
      - microservices-network
    command: ["java", "-jar", "eureka-server.jar"] # Am adăugat comanda de rulare

  # API Gateway, care rutează cererile și așteaptă toate celelalte servicii
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - SERVER_PORT=8080
    # Comanda crucială pentru a aștepta celelalte servicii
    command: ["sh", "-c", "./wait-for-it.sh eureka-server:8761 -- ./wait-for-it.sh user-service:8081 -- ./wait-for-it.sh product-service:8082 -- java -jar api-gateway.jar"]
    depends_on:
      - eureka-server
      - user-service
      - product-service
    restart: on-failure
    networks:
      - microservices-network

  # Serviciul pentru utilizatori
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - SERVER_PORT=8081
    depends_on:
      - eureka-server
    restart: on-failure
    networks:
      - microservices-network
    command: ["sh", "-c", "./wait-for-it.sh eureka-server:8761 -- java -jar user-service.jar"] # Am adăugat așteptare pentru Eureka

  # Serviciul pentru produse
  product-service:   
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka-server:8761/eureka
      - SERVER_PORT=8082
    depends_on:
      - eureka-server
    restart: on-failure
    networks:
      - microservices-network
    command: ["sh", "-c", "./wait-for-it.sh eureka-server:8761 -- java -jar product-service.jar"] # Am adăugat așteptare pentru Eureka

networks:
  microservices-network:
    driver: bridge
